/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export interface PartBase extends DevRev.AtomBase {
    /** The attached artifacts. */
    artifacts?: DevRev.ArtifactSummary[];
    /** Description of the part. */
    description?: string;
    /** Name of the part. */
    name?: string;
    /** The users that own the part. */
    ownedBy: DevRev.UserSummary[];
    stage?: DevRev.Stage;
    /** Tags associated with the object. */
    tags?: DevRev.TagWithValue[];
}
