/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export type PartsCreateRequest =
    | DevRev.PartsCreateRequest.Capability
    | DevRev.PartsCreateRequest.Feature
    | DevRev.PartsCreateRequest.Product;

export declare namespace PartsCreateRequest {
    interface Capability extends DevRev.PartsCreateRequestCapability, _Base {
        type: "capability";
    }

    interface Feature extends DevRev.PartsCreateRequestFeature, _Base {
        type: "feature";
    }

    interface Product extends DevRev.PartsCreateRequestProduct, _Base {
        type: "product";
    }

    interface _Base {
        /** Description of the part. */
        description?: string;
        /** Name of the part. */
        name?: string;
        /** The users that own the part. */
        ownedBy: string[];
    }
}
