/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export interface PartsCreateRequest {
    /** Description of the part. */
    description?: string;
    /** Name of the part. */
    name?: string;
    /** The users that own the part. */
    ownedBy: string[];
    type: DevRev.PartType;
}
