/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export type Part = DevRev.Part.Product;

export declare namespace Part {
    interface Product extends DevRev.Product {
        type: "product";
    }
}
