/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

/**
 * Request to create a new enterprise authentication connection.
 *
 */
export interface DevOrgAuthConnectionsCreateRequest {
    /**
     * Display name of the authentication connection. This name will be
     * visible to all the users when they sign in to this Dev
     * organization. For example, if the display_name is 'abclogin', then
     * it would appear on the login button as 'Log in to abclogin'.
     *
     */
    displayName?: string;
    type: DevRev.DevOrgAuthConnectionsCreateRequestType;
}
