/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { DevRev } from "@fern-api/devrev";

export class ServiceUnavailableError extends errors.DevRevError {
    constructor(body: DevRev.ServiceUnavailableErrorBody) {
        super({
            message: "service-unavailable-error",
            statusCode: 503,
            body: body,
        });
        Object.setPrototypeOf(this, ServiceUnavailableError.prototype);
    }
}
