/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { DevRev } from "@fern-api/devrev";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace RevOrgs {
    interface Options {
        environment?: environments.DevRevEnvironment | string;
        apiKey: core.Supplier<string>;
    }
}

/**
 * Rev organization interactions.
 */
export class RevOrgs {
    constructor(private readonly options: RevOrgs.Options) {}

    /**
     * Creates a Rev organization in the authenticated user's Dev
     * organization.
     *
     * @throws {DevRev.BadRequest}
     * @throws {DevRev.Unauthorized}
     * @throws {DevRev.Forbidden}
     * @throws {DevRev.NotFound}
     * @throws {DevRev.TooManyRequests}
     * @throws {DevRev.InternalServerError}
     * @throws {DevRev.ServiceUnavailable}
     */
    public async create(request: DevRev.RevOrgsCreateRequest): Promise<DevRev.RevOrgsCreateResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.DevRevEnvironment.Production, "rev-orgs.create"),
            method: "POST",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
            body: await serializers.RevOrgsCreateRequest.jsonOrThrow(request),
        });
        if (_response.ok) {
            return await serializers.RevOrgsCreateResponse.parseOrThrow(_response.body, { allowUnknownKeys: true });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DevRev.BadRequest(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 401:
                    throw new DevRev.Unauthorized(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 403:
                    throw new DevRev.Forbidden(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 404:
                    throw new DevRev.NotFound(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 429:
                    throw new DevRev.TooManyRequests(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 500:
                    throw new DevRev.InternalServerError(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 503:
                    throw new DevRev.ServiceUnavailable(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                default:
                    throw new errors.DevRevError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Deletes the Rev organization.
     * @throws {DevRev.BadRequest}
     * @throws {DevRev.Unauthorized}
     * @throws {DevRev.Forbidden}
     * @throws {DevRev.NotFound}
     * @throws {DevRev.TooManyRequests}
     * @throws {DevRev.InternalServerError}
     * @throws {DevRev.ServiceUnavailable}
     */
    public async delete(request: DevRev.RevOrgsDeleteRequest): Promise<DevRev.RevOrgsDeleteResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.DevRevEnvironment.Production, "rev-orgs.delete"),
            method: "POST",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
            body: await serializers.RevOrgsDeleteRequest.jsonOrThrow(request),
        });
        if (_response.ok) {
            return await serializers.RevOrgsDeleteResponse.parseOrThrow(_response.body, { allowUnknownKeys: true });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DevRev.BadRequest(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 401:
                    throw new DevRev.Unauthorized(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 403:
                    throw new DevRev.Forbidden(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 404:
                    throw new DevRev.NotFound(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 429:
                    throw new DevRev.TooManyRequests(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 500:
                    throw new DevRev.InternalServerError(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 503:
                    throw new DevRev.ServiceUnavailable(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                default:
                    throw new errors.DevRevError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Retrieves the Rev organization's information.
     * @throws {DevRev.BadRequest}
     * @throws {DevRev.Unauthorized}
     * @throws {DevRev.Forbidden}
     * @throws {DevRev.NotFound}
     * @throws {DevRev.TooManyRequests}
     * @throws {DevRev.InternalServerError}
     * @throws {DevRev.ServiceUnavailable}
     */
    public async get(request: DevRev.RevOrgsGetRequest): Promise<DevRev.RevOrgsGetResponse> {
        const { id } = request;
        const _queryParams = new URLSearchParams();
        _queryParams.append("id", id);
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.DevRevEnvironment.Production, "rev-orgs.get"),
            method: "GET",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.RevOrgsGetResponse.parseOrThrow(_response.body, { allowUnknownKeys: true });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DevRev.BadRequest(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 401:
                    throw new DevRev.Unauthorized(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 403:
                    throw new DevRev.Forbidden(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 404:
                    throw new DevRev.NotFound(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 429:
                    throw new DevRev.TooManyRequests(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 500:
                    throw new DevRev.InternalServerError(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 503:
                    throw new DevRev.ServiceUnavailable(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                default:
                    throw new errors.DevRevError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Gets the list of Rev organizations' information belonging to the
     * authenticated user's Dev Organization which the user is also authorized
     * to access.
     *
     * @throws {DevRev.BadRequest}
     * @throws {DevRev.Unauthorized}
     * @throws {DevRev.Forbidden}
     * @throws {DevRev.NotFound}
     * @throws {DevRev.TooManyRequests}
     * @throws {DevRev.InternalServerError}
     * @throws {DevRev.ServiceUnavailable}
     */
    public async list(request: DevRev.RevOrgsListRequest = {}): Promise<DevRev.RevOrgsListResponse> {
        const {
            createdBy,
            createdDateAfter,
            createdDateBefore,
            cursor,
            limit,
            mode,
            modifiedDateAfter,
            modifiedDateBefore,
            sortBy,
        } = request;
        const _queryParams = new URLSearchParams();
        if (createdBy != null) {
            if (Array.isArray(createdBy)) {
                for (const _item of createdBy) {
                    _queryParams.append("created_by", _item);
                }
            } else {
                _queryParams.append("created_by", createdBy);
            }
        }

        if (createdDateAfter != null) {
            _queryParams.append("created_date.after", createdDateAfter);
        }

        if (createdDateBefore != null) {
            _queryParams.append("created_date.before", createdDateBefore);
        }

        if (cursor != null) {
            _queryParams.append("cursor", cursor);
        }

        if (limit != null) {
            _queryParams.append("limit", limit.toString());
        }

        if (mode != null) {
            _queryParams.append("mode", mode);
        }

        if (modifiedDateAfter != null) {
            _queryParams.append("modified_date.after", modifiedDateAfter);
        }

        if (modifiedDateBefore != null) {
            _queryParams.append("modified_date.before", modifiedDateBefore);
        }

        if (sortBy != null) {
            if (Array.isArray(sortBy)) {
                for (const _item of sortBy) {
                    _queryParams.append("sort_by", _item);
                }
            } else {
                _queryParams.append("sort_by", sortBy);
            }
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.DevRevEnvironment.Production, "rev-orgs.list"),
            method: "GET",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.RevOrgsListResponse.parseOrThrow(_response.body, { allowUnknownKeys: true });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DevRev.BadRequest(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 401:
                    throw new DevRev.Unauthorized(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 403:
                    throw new DevRev.Forbidden(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 404:
                    throw new DevRev.NotFound(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 429:
                    throw new DevRev.TooManyRequests(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 500:
                    throw new DevRev.InternalServerError(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 503:
                    throw new DevRev.ServiceUnavailable(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                default:
                    throw new errors.DevRevError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Updates the Rev organization's information.
     * @throws {DevRev.BadRequest}
     * @throws {DevRev.Unauthorized}
     * @throws {DevRev.Forbidden}
     * @throws {DevRev.NotFound}
     * @throws {DevRev.TooManyRequests}
     * @throws {DevRev.InternalServerError}
     * @throws {DevRev.ServiceUnavailable}
     */
    public async update(request: DevRev.RevOrgsUpdateRequest): Promise<DevRev.RevOrgsUpdateResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.DevRevEnvironment.Production, "rev-orgs.update"),
            method: "POST",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
            body: await serializers.RevOrgsUpdateRequest.jsonOrThrow(request),
        });
        if (_response.ok) {
            return await serializers.RevOrgsUpdateResponse.parseOrThrow(_response.body, { allowUnknownKeys: true });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new DevRev.BadRequest(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 401:
                    throw new DevRev.Unauthorized(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 403:
                    throw new DevRev.Forbidden(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 404:
                    throw new DevRev.NotFound(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 429:
                    throw new DevRev.TooManyRequests(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 500:
                    throw new DevRev.InternalServerError(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                case 503:
                    throw new DevRev.ServiceUnavailable(
                        await serializers.ErrorBase.parseOrThrow(_response.error.body, { allowUnknownKeys: true })
                    );
                default:
                    throw new errors.DevRevError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
