/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const AuthTokensListResponse: core.serialization.ObjectSchema<
    serializers.AuthTokensListResponse.Raw,
    DevRev.AuthTokensListResponse
> = core.serialization.object({
    tokens: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).AuthToken)),
});

export declare namespace AuthTokensListResponse {
    interface Raw {
        tokens: serializers.AuthToken.Raw[];
    }
}
