/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const AuthTokensCreateResponse: core.serialization.ObjectSchema<
    serializers.AuthTokensCreateResponse.Raw,
    DevRev.AuthTokensCreateResponse
> = core.serialization.object({
    accessToken: core.serialization.property("access_token", core.serialization.string()),
    clientId: core.serialization.property("client_id", core.serialization.string().optional()),
    expiresIn: core.serialization.property("expires_in", core.serialization.number()),
    refreshToken: core.serialization.property("refresh_token", core.serialization.string().optional()),
    scope: core.serialization.string().optional(),
    tokenType: core.serialization.property(
        "token_type",
        core.serialization.lazy(async () => (await import("../../..")).AuthTokenTokenType)
    ),
});

export declare namespace AuthTokensCreateResponse {
    interface Raw {
        access_token: string;
        client_id?: string | null;
        expires_in: number;
        refresh_token?: string | null;
        scope?: string | null;
        token_type: serializers.AuthTokenTokenType.Raw;
    }
}
