/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const AuthTokensUpdateResponse: core.serialization.ObjectSchema<
    serializers.AuthTokensUpdateResponse.Raw,
    DevRev.AuthTokensUpdateResponse
> = core.serialization.object({
    token: core.serialization.lazyObject(async () => (await import("../../..")).AuthToken),
});

export declare namespace AuthTokensUpdateResponse {
    interface Raw {
        token: serializers.AuthToken.Raw;
    }
}
