/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const TagsCreateResponse: core.serialization.ObjectSchema<
    serializers.TagsCreateResponse.Raw,
    DevRev.TagsCreateResponse
> = core.serialization.object({
    tag: core.serialization.lazyObject(async () => (await import("../../..")).Tag),
});

export declare namespace TagsCreateResponse {
    interface Raw {
        tag: serializers.Tag.Raw;
    }
}
