/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";

const _Base = core.serialization.object({
    id: core.serialization.string(),
});
export const TimelineEntriesUpdateRequest: core.serialization.Schema<
    serializers.TimelineEntriesUpdateRequest.Raw,
    DevRev.TimelineEntriesUpdateRequest
> = core.serialization
    .union("type", {
        timeline_comment: core.serialization
            .lazyObject(async () => (await import("../../..")).TimelineEntriesUpdateRequestTimelineComment)
            .extend(_Base),
    })
    .transform<DevRev.TimelineEntriesUpdateRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace TimelineEntriesUpdateRequest {
    type Raw = TimelineEntriesUpdateRequest.TimelineComment;

    interface TimelineComment extends _Base, serializers.TimelineEntriesUpdateRequestTimelineComment.Raw {
        type: "timeline_comment";
    }

    interface _Base {
        id: string;
    }
}
