/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

/**
 * Response for the request to update the token metadata.
 */
export interface AuthTokensUpdateResponse {
    token: DevRev.AuthToken;
}
