/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export type PartSummary = DevRev.PartSummary.Product | DevRev.PartSummary._Unknown;

export declare namespace PartSummary {
    interface Product extends DevRev.ProductSummary {
        type: "product";
    }

    interface _Unknown {
        type: void;
    }

    interface _Visitor<_Result> {
        product: (value: DevRev.ProductSummary) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}
