/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export interface Ticket extends DevRev.WorkBase {
    revOrg?: DevRev.OrgSummary;
    severity?: DevRev.TicketSeverity;
}
