/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export interface WorksUpdateRequestTicket {
    /**
     * Updates the Rev organization that the ticket is associated with.
     *
     */
    revOrg?: string;
    severity?: DevRev.TicketSeverity;
}
