/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export type Work = DevRev.Work.Issue | DevRev.Work.Ticket;

export declare namespace Work {
    interface Issue extends DevRev.Issue {
        type: "issue";
    }

    interface Ticket extends DevRev.Ticket {
        type: "ticket";
    }
}
