/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export type Work = DevRev.Work.Issue | DevRev.Work.Ticket | DevRev.Work._Unknown;

export declare namespace Work {
    interface Issue extends DevRev.Issue {
        type: "issue";
    }

    interface Ticket extends DevRev.Ticket {
        type: "ticket";
    }

    interface _Unknown {
        type: void;
    }

    interface _Visitor<_Result> {
        issue: (value: DevRev.Issue) => _Result;
        ticket: (value: DevRev.Ticket) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}
