/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthTokensGetRequest {
    /**
     * The unique identifier of the token under a given Dev organization.
     *
     */
    tokenId: string;
}
