/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Defines the type for the authentication connection. The configuration
 * for each authentication connection will depend on the type value.
 *
 */
export type AuthConnectionType = "google_apps" | "oidc" | "samlp" | "social" | "waad";

export const AuthConnectionType = {
    GoogleApps: "google_apps",
    Oidc: "oidc",
    Samlp: "samlp",
    Social: "social",
    Waad: "waad",
} as const;
