/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

/**
 * Request to create a new enterprise authentication connection.
 *
 */
export type DevOrgAuthConnectionsCreateRequest =
    | DevRev.DevOrgAuthConnectionsCreateRequest.GoogleApps
    | DevRev.DevOrgAuthConnectionsCreateRequest.Oidc
    | DevRev.DevOrgAuthConnectionsCreateRequest.Samlp
    | DevRev.DevOrgAuthConnectionsCreateRequest.Waad;

export declare namespace DevOrgAuthConnectionsCreateRequest {
    interface GoogleApps extends DevRev.AuthConnectionOptionsGoogleApps {
        type: "google_apps";
    }

    interface Oidc extends DevRev.AuthConnectionOptionsOidc {
        type: "oidc";
    }

    interface Samlp extends DevRev.AuthConnectionOptionsSaml {
        type: "samlp";
    }

    interface Waad extends DevRev.AuthConnectionOptionsAzureAd {
        type: "waad";
    }
}
