/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specifies the type for the authentication connection. Different types
 * of authentication connections have different configuration parameters
 * that can be updated.
 *
 */
export type DevOrgAuthConnectionsUpdateRequestType = "google_apps" | "none" | "oidc" | "samlp" | "waad";

export const DevOrgAuthConnectionsUpdateRequestType = {
    GoogleApps: "google_apps",
    None: "none",
    Oidc: "oidc",
    Samlp: "samlp",
    Waad: "waad",
} as const;
