/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export interface DevUser extends DevRev.UserBase {
    /** IDs of the Dev User outside the DevRev SOR. */
    externalIdentities?: DevRev.ExternalIdentity[];
}
