/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export interface Enhancement extends DevRev.PartBase {
    /** Timestamp when the enhancement is expected to be closed. */
    targetCloseDate?: string;
}
