/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export interface ErrorInternalServerError {
    /**
     * A unique ID that's generated for the error that can be used for
     * inquiry.
     *
     */
    referenceId?: string;
    type?: DevRev.ErrorInternalServerErrorType;
}
