/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export type PartsUpdateRequest =
    | DevRev.PartsUpdateRequest.Capability
    | DevRev.PartsUpdateRequest.Enhancement
    | DevRev.PartsUpdateRequest.Feature
    | DevRev.PartsUpdateRequest.None
    | DevRev.PartsUpdateRequest.Product;

export declare namespace PartsUpdateRequest {
    interface Capability {
        type: "capability";
        value: DevRev.PartsUpdateRequestCapability;
    }

    interface Enhancement extends DevRev.PartsUpdateRequestEnhancement {
        type: "enhancement";
    }

    interface Feature {
        type: "feature";
        value: DevRev.PartsUpdateRequestFeature;
    }

    interface None {
        type: "none";
        value: DevRev.Empty;
    }

    interface Product {
        type: "product";
        value: DevRev.PartsUpdateRequestProduct;
    }
}
