/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PartsCreateRequestEnhancement {
    /**
     * ID of the parent part on which the enhancement is to be created.
     *
     */
    parentPart: string[];
    /**
     * Target close date by which enhancement is expected to be closed.
     *
     */
    targetCloseDate?: string;
}
