/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PartsUpdateRequestEnhancement {
    /** Updates the target close date of the enhancement. */
    targetCloseDate?: string;
}
