/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

/**
 * The response for updating a tag.
 */
export interface TagsUpdateResponse {
    tag: DevRev.Tag;
}
