/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export interface TagWithValue {
    tag: DevRev.TagSummary;
    /** The value for the object's association with the tag. */
    value?: string;
}
