/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export interface Ticket extends DevRev.WorkBase {
    group?: DevRev.GroupSummary;
    revOrg?: DevRev.OrgSummary;
    severity?: DevRev.TicketSeverity;
}
