/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

/**
 * The request to create a timeline entry for an object.
 */
export type TimelineEntriesCreateRequest = DevRev.TimelineEntriesCreateRequest.TimelineComment;

export declare namespace TimelineEntriesCreateRequest {
    interface TimelineComment extends DevRev.TimelineEntriesCreateRequestTimelineComment {
        type: "timeline_comment";
    }
}
