/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The visibility of the entry. If 'private', then the entry is only
 * visible to the creator, otherwise if not set, then the entry has
 * default visibility.
 *
 */
export type TimelineEntryVisibility = "private";

export const TimelineEntryVisibility = {
    Private: "private",
} as const;
