/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The event types that the webhook will receive.
 */
export type WebhookEventType =
    | "part_created"
    | "part_deleted"
    | "part_updated"
    | "rev_org_created"
    | "rev_org_deleted"
    | "rev_org_updated"
    | "tag_created"
    | "tag_deleted"
    | "tag_updated"
    | "timeline_entry_created"
    | "timeline_entry_deleted"
    | "timeline_entry_updated"
    | "verify"
    | "webhook_created"
    | "webhook_deleted"
    | "webhook_updated"
    | "work_created"
    | "work_deleted"
    | "work_updated";

export const WebhookEventType = {
    PartCreated: "part_created",
    PartDeleted: "part_deleted",
    PartUpdated: "part_updated",
    RevOrgCreated: "rev_org_created",
    RevOrgDeleted: "rev_org_deleted",
    RevOrgUpdated: "rev_org_updated",
    TagCreated: "tag_created",
    TagDeleted: "tag_deleted",
    TagUpdated: "tag_updated",
    TimelineEntryCreated: "timeline_entry_created",
    TimelineEntryDeleted: "timeline_entry_deleted",
    TimelineEntryUpdated: "timeline_entry_updated",
    Verify: "verify",
    WebhookCreated: "webhook_created",
    WebhookDeleted: "webhook_deleted",
    WebhookUpdated: "webhook_updated",
    WorkCreated: "work_created",
    WorkDeleted: "work_deleted",
    WorkUpdated: "work_updated",
} as const;
