/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export interface WebhookEventRequest {
    /** The event's ID. */
    id: string;
    partCreated?: DevRev.EventPartCreated;
    partDeleted?: DevRev.EventPartDeleted;
    partUpdated?: DevRev.EventPartUpdated;
    revOrgCreated?: DevRev.EventRevOrgCreated;
    revOrgDeleted?: DevRev.EventRevOrgDeleted;
    revOrgUpdated?: DevRev.EventRevOrgUpdated;
    tagCreated?: DevRev.EventTagCreated;
    tagDeleted?: DevRev.EventTagDeleted;
    tagUpdated?: DevRev.EventTagUpdated;
    timelineEntryCreated?: DevRev.EventTimelineEntryCreated;
    timelineEntryDeleted?: DevRev.EventTimelineEntryDeleted;
    timelineEntryUpdated?: DevRev.EventTimelineEntryUpdated;
    /**
     * Timestamp of the webhook's invocation for the event. Note this
     * should be used to protect against replay attacks, where the event
     * should only be processed if the timestamp isn't stale by several
     * seconds.
     *
     */
    timestamp?: string;
    type?: DevRev.WebhookEventType;
    verify?: DevRev.WebhookEventVerify;
    webhookCreated?: DevRev.EventWebhookCreated;
    webhookDeleted?: DevRev.EventWebhookDeleted;
    /** ID of the webhook for the event. */
    webhookId: string;
    webhookUpdated?: DevRev.EventWebhookUpdated;
    workCreated?: DevRev.EventWorkCreated;
    workDeleted?: DevRev.EventWorkDeleted;
    workUpdated?: DevRev.EventWorkUpdated;
}
