/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export interface WorksCreateRequestIssue {
    priority?: DevRev.IssuePriority;
    /** The sprint that the issue belongs to. */
    sprint?: string;
}
