/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export type WorksCreateRequest = DevRev.WorksCreateRequest.Issue | DevRev.WorksCreateRequest.Ticket;

export declare namespace WorksCreateRequest {
    interface Issue extends DevRev.WorksCreateRequestIssue {
        type: "issue";
    }

    interface Ticket extends DevRev.WorksCreateRequestTicket {
        type: "ticket";
    }
}
