/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "..";

export type WorksUpdateRequest =
    | DevRev.WorksUpdateRequest.Issue
    | DevRev.WorksUpdateRequest.None
    | DevRev.WorksUpdateRequest.Ticket;

export declare namespace WorksUpdateRequest {
    interface Issue extends DevRev.WorksUpdateRequestIssue {
        type: "issue";
    }

    interface None {
        type: "none";
        value: DevRev.Empty;
    }

    interface Ticket extends DevRev.WorksUpdateRequestTicket {
        type: "ticket";
    }
}
