/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

/**
 * Response object for request to create a new Rev organization.
 *
 */
export interface RevOrgsCreateResponse {
    revOrg: DevRev.RevOrg;
}
