/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

/**
 * The response to getting a Rev organization's information.
 */
export interface RevOrgsGetResponse {
    revOrg: DevRev.RevOrg;
}
