/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

/**
 * Request object to update information of the Rev organization.
 *
 */
export interface RevOrgsUpdateRequest {
    /** Description of the Rev organization. */
    description?: string;
    /** Customer chosen name for the Rev organization. */
    displayName?: string;
    /** Company's domain name. Example - 'devrev.ai'. */
    domain?: string;
    environment?: DevRev.OrgEnvironment;
    /**
     * External ref is a custom unique identifier which is a reference to
     * an unique id for this organization's data in some system of
     * records.
     *
     */
    externalRef?: string;
    /** The ID of Rev organization to update. */
    id: string;
}
