/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const PartsCreateRequestFeature: core.serialization.ObjectSchema<
    serializers.PartsCreateRequestFeature.Raw,
    DevRev.PartsCreateRequestFeature
> = core.serialization.object({});

export declare namespace PartsCreateRequestFeature {
    interface Raw {}
}
