/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";

const _Base = core.serialization.object({
    description: core.serialization.string().optional(),
    id: core.serialization.string(),
    name: core.serialization.string().optional(),
    type: core.serialization.lazy(async () => (await import("../../..")).PartType),
});
export const PartsUpdateRequest: core.serialization.Schema<
    serializers.PartsUpdateRequest.Raw,
    DevRev.PartsUpdateRequest
> = core.serialization
    .union("type", {
        capability: core.serialization
            .object({
                value: core.serialization.lazy(async () => (await import("../../..")).PartsUpdateRequestCapability),
            })
            .extend(_Base),
        feature: core.serialization
            .object({
                value: core.serialization.lazy(async () => (await import("../../..")).PartsUpdateRequestFeature),
            })
            .extend(_Base),
        none: core.serialization.object({}).extend(_Base),
        product: core.serialization
            .object({
                value: core.serialization.lazy(async () => (await import("../../..")).PartsUpdateRequestProduct),
            })
            .extend(_Base),
    })
    .transform<DevRev.PartsUpdateRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace PartsUpdateRequest {
    type Raw =
        | PartsUpdateRequest.Capability
        | PartsUpdateRequest.Feature
        | PartsUpdateRequest.None
        | PartsUpdateRequest.Product;

    interface Capability extends _Base {
        type: "capability";
        value: serializers.PartsUpdateRequestCapability.Raw;
    }

    interface Feature extends _Base {
        type: "feature";
        value: serializers.PartsUpdateRequestFeature.Raw;
    }

    interface None extends _Base {
        type: "none";
    }

    interface Product extends _Base {
        type: "product";
        value: serializers.PartsUpdateRequestProduct.Raw;
    }

    interface _Base {
        description?: string;
        id: string;
        name?: string;
        type: DevRev.PartType;
    }
}
