/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const PartsUpdateResponse: core.serialization.ObjectSchema<
    serializers.PartsUpdateResponse.Raw,
    DevRev.PartsUpdateResponse
> = core.serialization.object({
    part: core.serialization.lazyObject(async () => (await import("../../..")).Part),
});

export declare namespace PartsUpdateResponse {
    interface Raw {
        part: serializers.Part.Raw;
    }
}
