/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const PartsDeleteRequest: core.serialization.ObjectSchema<
    serializers.PartsDeleteRequest.Raw,
    DevRev.PartsDeleteRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace PartsDeleteRequest {
    interface Raw {
        id: string;
    }
}
