/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const PartsCreateRequestProduct: core.serialization.ObjectSchema<
    serializers.PartsCreateRequestProduct.Raw,
    DevRev.PartsCreateRequestProduct
> = core.serialization.object({});

export declare namespace PartsCreateRequestProduct {
    interface Raw {}
}
