/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const AuthConnectionOptionsGoogleApps: core.serialization.ObjectSchema<
    serializers.AuthConnectionOptionsGoogleApps.Raw,
    DevRev.AuthConnectionOptionsGoogleApps
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string().optional()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string().optional()),
    tenantDomain: core.serialization.property("tenant_domain", core.serialization.string().optional()),
});

export declare namespace AuthConnectionOptionsGoogleApps {
    interface Raw {
        client_id?: string | null;
        client_secret?: string | null;
        tenant_domain?: string | null;
    }
}
