/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const DevOrgAuthConnectionsCreateResponse: core.serialization.ObjectSchema<
    serializers.DevOrgAuthConnectionsCreateResponse.Raw,
    DevRev.DevOrgAuthConnectionsCreateResponse
> = core.serialization.object({
    authConnection: core.serialization.property(
        "auth_connection",
        core.serialization.lazy(async () => (await import("../../..")).AuthConnection)
    ),
});

export declare namespace DevOrgAuthConnectionsCreateResponse {
    interface Raw {
        auth_connection: serializers.AuthConnection.Raw;
    }
}
