/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const WebhooksCreateResponse: core.serialization.ObjectSchema<
    serializers.WebhooksCreateResponse.Raw,
    DevRev.WebhooksCreateResponse
> = core.serialization.object({
    webhook: core.serialization.lazyObject(async () => (await import("../../..")).Webhook),
});

export declare namespace WebhooksCreateResponse {
    interface Raw {
        webhook: serializers.Webhook.Raw;
    }
}
