/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import { DevRev } from "@fern-api/devrev";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Tags {
    interface Options {
        environment: string;
        authorization?: core.Supplier<string>;
    }
}

export class Tags {
    constructor(private readonly options: Tags.Options) {}

    /**
     * Creates a new tag, which is used to create associations between objects
     * and a logical concept denoted by the tag's name.
     *
     */
    public async create(request: DevRev.TagsCreateRequest): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "tags.create"),
            method: "POST",
            headers: {
                Authorization: await core.Supplier.get(this.options.authorization),
            },
            body: await serializers.TagsCreateRequest.jsonOrThrow(request),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.DevRevError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Deletes a tag.
     */
    public async delete(request: DevRev.TagsDeleteRequest): Promise<DevRev.TagsDeleteResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "tags.delete"),
            method: "POST",
            headers: {
                Authorization: await core.Supplier.get(this.options.authorization),
            },
            body: await serializers.TagsDeleteRequest.jsonOrThrow(request),
        });
        if (_response.ok) {
            return await serializers.TagsDeleteResponse.parseOrThrow(
                _response.body as serializers.TagsDeleteResponse.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.DevRevError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Gets a tag's information.
     */
    public async get(request: DevRev.TagsGetRequest): Promise<DevRev.TagsGetResponse> {
        const { id } = request;
        const _queryParams = new URLSearchParams();
        _queryParams.append("id", id);
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "tags.get"),
            method: "GET",
            headers: {
                Authorization: await core.Supplier.get(this.options.authorization),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.TagsGetResponse.parseOrThrow(_response.body as serializers.TagsGetResponse.Raw, {
                allowUnknownKeys: true,
            });
        }

        if (_response.error.reason === "status-code") {
            throw new errors.DevRevError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Lists the available tags.
     */
    public async list(request: DevRev.TagsListRequest = {}): Promise<DevRev.TagsListResponse> {
        const { cursor, limit, mode } = request;
        const _queryParams = new URLSearchParams();
        if (cursor != null) {
            _queryParams.append("cursor", cursor);
        }

        if (limit != null) {
            _queryParams.append("limit", limit.toString());
        }

        if (mode != null) {
            _queryParams.append("mode", mode);
        }

        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "tags.list"),
            method: "GET",
            headers: {
                Authorization: await core.Supplier.get(this.options.authorization),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.TagsListResponse.parseOrThrow(_response.body as serializers.TagsListResponse.Raw, {
                allowUnknownKeys: true,
            });
        }

        if (_response.error.reason === "status-code") {
            throw new errors.DevRevError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Updates a tag's information.
     */
    public async update(request: DevRev.TagsUpdateRequest): Promise<DevRev.TagsUpdateResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "tags.update"),
            method: "POST",
            headers: {
                Authorization: await core.Supplier.get(this.options.authorization),
            },
            body: await serializers.TagsUpdateRequest.jsonOrThrow(request),
        });
        if (_response.ok) {
            return await serializers.TagsUpdateResponse.parseOrThrow(
                _response.body as serializers.TagsUpdateResponse.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.DevRevError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.DevRevError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.DevRevTimeoutError();
            case "unknown":
                throw new errors.DevRevError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
