/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const AuthConnectionOptionsSocial: core.serialization.Schema<
    serializers.AuthConnectionOptionsSocial.Raw,
    DevRev.AuthConnectionOptionsSocial
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace AuthConnectionOptionsSocial {
    type Raw = Record<string, unknown>;
}
