/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const AuthTokenTokenType: core.serialization.Schema<
    serializers.AuthTokenTokenType.Raw,
    DevRev.AuthTokenTokenType
> = core.serialization.enum_(["bearer"]);

export declare namespace AuthTokenTokenType {
    type Raw = "bearer";
}
