/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const AuthTokensRevInfo: core.serialization.ObjectSchema<
    serializers.AuthTokensRevInfo.Raw,
    DevRev.AuthTokensRevInfo
> = core.serialization.object({
    orgRef: core.serialization.property("org_ref", core.serialization.string().optional()),
    orgTraits: core.serialization.property(
        "org_traits",
        core.serialization.lazyObject(async () => (await import("..")).AuthTokensOrgTraits).optional()
    ),
    userId: core.serialization.property("user_id", core.serialization.string().optional()),
    userRef: core.serialization.property("user_ref", core.serialization.string().optional()),
    userTraits: core.serialization.property(
        "user_traits",
        core.serialization.lazyObject(async () => (await import("..")).AuthTokensUserTraits).optional()
    ),
});

export declare namespace AuthTokensRevInfo {
    interface Raw {
        org_ref?: string | null;
        org_traits?: serializers.AuthTokensOrgTraits.Raw | null;
        user_id?: string | null;
        user_ref?: string | null;
        user_traits?: serializers.AuthTokensUserTraits.Raw | null;
    }
}
