/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const AuthConnectionOptionsAzureAd: core.serialization.ObjectSchema<
    serializers.AuthConnectionOptionsAzureAd.Raw,
    DevRev.AuthConnectionOptionsAzureAd
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string().optional()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string().optional()),
    domain: core.serialization.string().optional(),
});

export declare namespace AuthConnectionOptionsAzureAd {
    interface Raw {
        client_id?: string | null;
        client_secret?: string | null;
        domain?: string | null;
    }
}
