/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const DevOrgAuthConnectionsUpdateResponse: core.serialization.ObjectSchema<
    serializers.DevOrgAuthConnectionsUpdateResponse.Raw,
    DevRev.DevOrgAuthConnectionsUpdateResponse
> = core.serialization.object({
    authConnection: core.serialization.property(
        "auth_connection",
        core.serialization.lazy(async () => (await import("..")).AuthConnection)
    ),
});

export declare namespace DevOrgAuthConnectionsUpdateResponse {
    interface Raw {
        auth_connection: serializers.AuthConnection.Raw;
    }
}
