/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const DevOrgAuthConnectionsCreateRequestType: core.serialization.Schema<
    serializers.DevOrgAuthConnectionsCreateRequestType.Raw,
    DevRev.DevOrgAuthConnectionsCreateRequestType
> = core.serialization.enum_(["google_apps", "oidc", "samlp", "waad"]);

export declare namespace DevOrgAuthConnectionsCreateRequestType {
    type Raw = "google_apps" | "oidc" | "samlp" | "waad";
}
