/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const ErrorNotFoundType: core.serialization.Schema<serializers.ErrorNotFoundType.Raw, DevRev.ErrorNotFoundType> =
    core.serialization.enum_(["not_found"]);

export declare namespace ErrorNotFoundType {
    type Raw = "not_found";
}
