/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const EventTagUpdated: core.serialization.ObjectSchema<serializers.EventTagUpdated.Raw, DevRev.EventTagUpdated> =
    core.serialization.object({
        tag: core.serialization.lazyObject(async () => (await import("..")).Tag),
    });

export declare namespace EventTagUpdated {
    interface Raw {
        tag: serializers.Tag.Raw;
    }
}
