/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const EventWorkUpdated: core.serialization.ObjectSchema<
    serializers.EventWorkUpdated.Raw,
    DevRev.EventWorkUpdated
> = core.serialization.object({
    work: core.serialization.lazy(async () => (await import("..")).Work),
});

export declare namespace EventWorkUpdated {
    interface Raw {
        work: serializers.Work.Raw;
    }
}
