/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const EventTimelineEntryUpdated: core.serialization.ObjectSchema<
    serializers.EventTimelineEntryUpdated.Raw,
    DevRev.EventTimelineEntryUpdated
> = core.serialization.object({
    entry: core.serialization.lazy(async () => (await import("..")).TimelineEntry),
});

export declare namespace EventTimelineEntryUpdated {
    interface Raw {
        entry: serializers.TimelineEntry.Raw;
    }
}
