/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const EventWebhookCreated: core.serialization.ObjectSchema<
    serializers.EventWebhookCreated.Raw,
    DevRev.EventWebhookCreated
> = core.serialization.object({
    webhook: core.serialization.lazyObject(async () => (await import("..")).Webhook),
});

export declare namespace EventWebhookCreated {
    interface Raw {
        webhook: serializers.Webhook.Raw;
    }
}
