/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const EventTimelineEntryDeleted: core.serialization.ObjectSchema<
    serializers.EventTimelineEntryDeleted.Raw,
    DevRev.EventTimelineEntryDeleted
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace EventTimelineEntryDeleted {
    interface Raw {
        id: string;
    }
}
