/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const Issue: core.serialization.ObjectSchema<serializers.Issue.Raw, DevRev.Issue> = core.serialization
    .object({
        priority: core.serialization.lazy(async () => (await import("..")).IssuePriority).optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).WorkBase));

export declare namespace Issue {
    interface Raw extends serializers.WorkBase.Raw {
        priority?: serializers.IssuePriority.Raw | null;
    }
}
