/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const PartsCreateResponse: core.serialization.ObjectSchema<
    serializers.PartsCreateResponse.Raw,
    DevRev.PartsCreateResponse
> = core.serialization.object({
    part: core.serialization.lazy(async () => (await import("..")).Part),
});

export declare namespace PartsCreateResponse {
    interface Raw {
        part: serializers.Part.Raw;
    }
}
