/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../core";
import * as serializers from "..";
import * as DevRev from "../../api";

const _Base = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).PartType),
});
export const PartSummary: core.serialization.Schema<serializers.PartSummary.Raw, DevRev.PartSummary> =
    core.serialization
        .union("type", {
            capability: core.serialization.lazyObject(async () => (await import("..")).PartBaseSummary).extend(_Base),
            enhancement: core.serialization.lazyObject(async () => (await import("..")).PartBaseSummary).extend(_Base),
            feature: core.serialization.lazyObject(async () => (await import("..")).PartBaseSummary).extend(_Base),
            product: core.serialization.lazyObject(async () => (await import("..")).PartBaseSummary).extend(_Base),
        })
        .transform<DevRev.PartSummary>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace PartSummary {
    type Raw = PartSummary.Capability | PartSummary.Enhancement | PartSummary.Feature | PartSummary.Product;

    interface Capability extends _Base, serializers.PartBaseSummary.Raw {
        type: "capability";
    }

    interface Enhancement extends _Base, serializers.PartBaseSummary.Raw {
        type: "enhancement";
    }

    interface Feature extends _Base, serializers.PartBaseSummary.Raw {
        type: "feature";
    }

    interface Product extends _Base, serializers.PartBaseSummary.Raw {
        type: "product";
    }

    interface _Base {
        type: serializers.PartType.Raw;
    }
}
