/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../core";
import * as serializers from "..";
import * as DevRev from "../../api";

const _Base = core.serialization.object({
    description: core.serialization.string().optional(),
    id: core.serialization.string(),
    name: core.serialization.string().optional(),
    ownedBy: core.serialization.property(
        "owned_by",
        core.serialization.lazyObject(async () => (await import("..")).PartsUpdateRequestOwnedBy).optional()
    ),
    type: core.serialization.lazy(async () => (await import("..")).PartType),
});
export const PartsUpdateRequest: core.serialization.Schema<
    serializers.PartsUpdateRequest.Raw,
    DevRev.PartsUpdateRequest
> = core.serialization
    .union("type", {
        capability: core.serialization
            .object({
                value: core.serialization.lazy(async () => (await import("..")).PartsUpdateRequestCapability),
            })
            .extend(_Base),
        enhancement: core.serialization
            .lazyObject(async () => (await import("..")).PartsUpdateRequestEnhancement)
            .extend(_Base),
        feature: core.serialization
            .object({
                value: core.serialization.lazy(async () => (await import("..")).PartsUpdateRequestFeature),
            })
            .extend(_Base),
        none: core.serialization
            .object({
                value: core.serialization.lazy(async () => (await import("..")).Empty),
            })
            .extend(_Base),
        product: core.serialization
            .object({
                value: core.serialization.lazy(async () => (await import("..")).PartsUpdateRequestProduct),
            })
            .extend(_Base),
    })
    .transform<DevRev.PartsUpdateRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace PartsUpdateRequest {
    type Raw =
        | PartsUpdateRequest.Capability
        | PartsUpdateRequest.Enhancement
        | PartsUpdateRequest.Feature
        | PartsUpdateRequest.None
        | PartsUpdateRequest.Product;

    interface Capability extends _Base {
        type: "capability";
        value: serializers.PartsUpdateRequestCapability.Raw;
    }

    interface Enhancement extends _Base, serializers.PartsUpdateRequestEnhancement.Raw {
        type: "enhancement";
    }

    interface Feature extends _Base {
        type: "feature";
        value: serializers.PartsUpdateRequestFeature.Raw;
    }

    interface None extends _Base {
        type: "none";
        value: serializers.Empty.Raw;
    }

    interface Product extends _Base {
        type: "product";
        value: serializers.PartsUpdateRequestProduct.Raw;
    }

    interface _Base {
        description?: string | null;
        id: string;
        name?: string | null;
        owned_by?: serializers.PartsUpdateRequestOwnedBy.Raw | null;
        type: serializers.PartType.Raw;
    }
}
