/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const Product: core.serialization.ObjectSchema<serializers.Product.Raw, DevRev.Product> =
    core.serialization.lazyObject(async () => (await import("..")).PartBase);

export declare namespace Product {
    type Raw = serializers.PartBase.Raw;
}
