/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const TagsUpdateResponse: core.serialization.ObjectSchema<
    serializers.TagsUpdateResponse.Raw,
    DevRev.TagsUpdateResponse
> = core.serialization.object({
    tag: core.serialization.lazyObject(async () => (await import("..")).Tag),
});

export declare namespace TagsUpdateResponse {
    interface Raw {
        tag: serializers.Tag.Raw;
    }
}
