/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const TimelineEntryVisibility: core.serialization.Schema<
    serializers.TimelineEntryVisibility.Raw,
    DevRev.TimelineEntryVisibility
> = core.serialization.enum_(["private"]);

export declare namespace TimelineEntryVisibility {
    type Raw = "private";
}
