/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const TimelineEntriesListResponse: core.serialization.ObjectSchema<
    serializers.TimelineEntriesListResponse.Raw,
    DevRev.TimelineEntriesListResponse
> = core.serialization.object({
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
    timelineEntries: core.serialization.property(
        "timeline_entries",
        core.serialization.list(core.serialization.lazy(async () => (await import("..")).TimelineEntry))
    ),
});

export declare namespace TimelineEntriesListResponse {
    interface Raw {
        next_cursor?: string | null;
        prev_cursor?: string | null;
        timeline_entries: serializers.TimelineEntry.Raw[];
    }
}
