/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const WebhookEventType: core.serialization.Schema<serializers.WebhookEventType.Raw, DevRev.WebhookEventType> =
    core.serialization.enum_([
        "part_created",
        "part_deleted",
        "part_updated",
        "rev_org_created",
        "rev_org_deleted",
        "rev_org_updated",
        "tag_created",
        "tag_deleted",
        "tag_updated",
        "timeline_entry_created",
        "timeline_entry_deleted",
        "timeline_entry_updated",
        "verify",
        "webhook_created",
        "webhook_deleted",
        "webhook_updated",
        "work_created",
        "work_deleted",
        "work_updated",
    ]);

export declare namespace WebhookEventType {
    type Raw =
        | "part_created"
        | "part_deleted"
        | "part_updated"
        | "rev_org_created"
        | "rev_org_deleted"
        | "rev_org_updated"
        | "tag_created"
        | "tag_deleted"
        | "tag_updated"
        | "timeline_entry_created"
        | "timeline_entry_deleted"
        | "timeline_entry_updated"
        | "verify"
        | "webhook_created"
        | "webhook_deleted"
        | "webhook_updated"
        | "work_created"
        | "work_deleted"
        | "work_updated";
}
