/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const WebhookEventVerify: core.serialization.ObjectSchema<
    serializers.WebhookEventVerify.Raw,
    DevRev.WebhookEventVerify
> = core.serialization.object({
    challenge: core.serialization.string(),
});

export declare namespace WebhookEventVerify {
    interface Raw {
        challenge: string;
    }
}
