/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRev from "../../api";
import * as core from "../../core";

export const WorksExportResponse: core.serialization.ObjectSchema<
    serializers.WorksExportResponse.Raw,
    DevRev.WorksExportResponse
> = core.serialization.object({
    works: core.serialization.list(core.serialization.lazy(async () => (await import("..")).Work)),
});

export declare namespace WorksExportResponse {
    interface Raw {
        works: serializers.Work.Raw[];
    }
}
