/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const DevUsersListResponse: core.serialization.ObjectSchema<
    serializers.DevUsersListResponse.Raw,
    DevRev.DevUsersListResponse
> = core.serialization.object({
    devUsers: core.serialization.property(
        "dev_users",
        core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).DevUser))
    ),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
});

export declare namespace DevUsersListResponse {
    interface Raw {
        dev_users: serializers.DevUser.Raw[];
        next_cursor?: string | null;
        prev_cursor?: string | null;
    }
}
