/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Carries Rev user info.
 */
export interface AuthTokensUserTraits {
    /** The display name of the Rev user. */
    displayName?: string;
    /** The email address of the Rev user. */
    email?: string;
    /** The full name of the Rev user. */
    fullName?: string;
}
