/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of the subject token.
 */
export type AuthTokenSubjectTokenType =
    | "urn:devrev:params:oauth:token-type:jwt:auth0"
    | "urn:devrev:params:oauth:token-type:jwt:dev"
    | "urn:devrev:params:oauth:token-type:revinfo"
    | "urn:devrev:params:oauth:token-type:sysu"
    | "urn:devrev:params:oauth:token-type:userinfo"
    | "urn:devrev:params:oauth:token-type:userinfo:profile"
    | "urn:ietf:params:oauth:token-type:jwt";

export const AuthTokenSubjectTokenType = {
    TokenTypeJwtAuth0: "urn:devrev:params:oauth:token-type:jwt:auth0",
    TokenTypeJwtRevinfo: "urn:devrev:params:oauth:token-type:jwt:dev",
    TokenTypeRevinfo: "urn:devrev:params:oauth:token-type:revinfo",
    TokenTypeSysu: "urn:devrev:params:oauth:token-type:sysu",
    TokenTypeUserinfo: "urn:devrev:params:oauth:token-type:userinfo",
    TokenTypeUserinfoProfile: "urn:devrev:params:oauth:token-type:userinfo:profile",
    TokenTypeJwt: "urn:ietf:params:oauth:token-type:jwt",
} as const;
