/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object encapsulating the configuration parameters for a SAML
 * authentication connection.
 *
 */
export interface AuthConnectionOptionsSaml {
    /** Sign In endpoint for the SAML authentication connection. */
    signInEndpoint?: string;
    /**
     * Signing certificate for the SAML authentication connection.
     *
     */
    signingCert?: string;
}
