/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

/**
 * Connection object that specifies the configuration for an
 * authentication connection that is set up for a Dev organization.
 *
 */
export interface AuthConnection {
    /**
     * Display name of the authentication connection. This name will be
     * visible to all the users when they sign in to this Dev
     * organization. For example, if the display_name is 'abclogin', then
     * it would appear on the login button as 'Log in to abclogin'.
     *
     */
    displayName?: string;
    /**
     * Whether the authentication connection is enabled or disabled. If
     * set to false, the authentication connection will not show up on the
     * login screen as a login option.
     *
     */
    enabled?: boolean;
    /** ID of the authentication connection. */
    id: string;
    type: DevRev.AuthConnectionType;
}
