/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export interface RevUserSummary extends DevRev.UserBaseSummary {
    revOrg?: DevRev.OrgSummary;
}
