/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export type ServiceUnavailableErrorBody = DevRev.ServiceUnavailableErrorBody.ServiceUnavailable;

export declare namespace ServiceUnavailableErrorBody {
    interface ServiceUnavailable extends _Base {
        type: "service_unavailable";
    }

    interface _Base {
        /** The message associated with the error. */
        message?: string;
    }
}
