/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export interface TimelineComment extends DevRev.TimelineEntryBase {
    /**
     * The comment's body. If the comment has been deleted, then no body
     * will appear in the response.
     *
     */
    body?: string;
    bodyType?: DevRev.TimelineCommentBodyType;
    /** The SnapKit Body of the comment. */
    snapKitBody?: Record<string, unknown>;
}
