/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export interface TimelineEntriesCreateRequestTimelineComment {
    /** The comment's body. */
    body?: string;
    bodyType?: DevRev.TimelineCommentBodyType;
    /** The SnapKit body of the comment. */
    snapKitBody?: Record<string, unknown>;
}
