/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DevRev } from "@fern-api/devrev";

export type UserSummary = DevRev.UserSummary.DevUser | DevRev.UserSummary.RevUser | DevRev.UserSummary.SysUser;

export declare namespace UserSummary {
    interface DevUser extends DevRev.DevUserSummary {
        type: "dev_user";
    }

    interface RevUser extends DevRev.RevUserSummary {
        type: "rev_user";
    }

    interface SysUser extends DevRev.SysUserSummary {
        type: "sys_user";
    }
}
