/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const WorksUpdateRequestIssue: core.serialization.ObjectSchema<
    serializers.WorksUpdateRequestIssue.Raw,
    DevRev.WorksUpdateRequestIssue
> = core.serialization.object({
    priority: core.serialization.lazy(async () => (await import("../../..")).IssuePriority).optional(),
});

export declare namespace WorksUpdateRequestIssue {
    interface Raw {
        priority?: serializers.IssuePriority.Raw | null;
    }
}
