/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const WorksUpdateRequestTags: core.serialization.ObjectSchema<
    serializers.WorksUpdateRequestTags.Raw,
    DevRev.WorksUpdateRequestTags
> = core.serialization.object({
    set: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).SetTagWithValue))
        .optional(),
});

export declare namespace WorksUpdateRequestTags {
    interface Raw {
        set?: serializers.SetTagWithValue.Raw[] | null;
    }
}
