/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const WorksCreateRequestTicket: core.serialization.ObjectSchema<
    serializers.WorksCreateRequestTicket.Raw,
    DevRev.WorksCreateRequestTicket
> = core.serialization.object({
    revOrg: core.serialization.property("rev_org", core.serialization.string().optional()),
    severity: core.serialization.lazy(async () => (await import("../../..")).TicketSeverity).optional(),
    appliesToPart: core.serialization.property("applies_to_part", core.serialization.string()),
    artifacts: core.serialization.list(core.serialization.string()).optional(),
    body: core.serialization.string().optional(),
    ownedBy: core.serialization.property("owned_by", core.serialization.list(core.serialization.string())),
    reportedBy: core.serialization.property(
        "reported_by",
        core.serialization.list(core.serialization.string()).optional()
    ),
    stage: core.serialization.lazyObject(async () => (await import("../../..")).StageInit).optional(),
    tags: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).SetTagWithValue))
        .optional(),
    targetCloseDate: core.serialization.property("target_close_date", core.serialization.string().optional()),
    title: core.serialization.string(),
});

export declare namespace WorksCreateRequestTicket {
    interface Raw {
        rev_org?: string | null;
        severity?: serializers.TicketSeverity.Raw | null;
        applies_to_part: string;
        artifacts?: string[] | null;
        body?: string | null;
        owned_by: string[];
        reported_by?: string[] | null;
        stage?: serializers.StageInit.Raw | null;
        tags?: serializers.SetTagWithValue.Raw[] | null;
        target_close_date?: string | null;
        title: string;
    }
}
