/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const DevUser: core.serialization.ObjectSchema<serializers.DevUser.Raw, DevRev.DevUser> = core.serialization
    .object({
        externalIdentities: core.serialization.property(
            "external_identities",
            core.serialization
                .list(core.serialization.lazy(async () => (await import("../../..")).ExternalIdentity))
                .optional()
        ),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).UserBase));

export declare namespace DevUser {
    interface Raw extends serializers.UserBase.Raw {
        external_identities?: serializers.ExternalIdentity.Raw[] | null;
    }
}
