/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const SysUserSummary: core.serialization.ObjectSchema<serializers.SysUserSummary.Raw, DevRev.SysUserSummary> =
    core.serialization
        .object({})
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).UserBaseSummary));

export declare namespace SysUserSummary {
    interface Raw extends serializers.UserBaseSummary.Raw {}
}
