/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const TagSummary: core.serialization.ObjectSchema<serializers.TagSummary.Raw, DevRev.TagSummary> =
    core.serialization
        .object({
            name: core.serialization.string(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).AtomBaseSummary));

export declare namespace TagSummary {
    interface Raw extends serializers.AtomBaseSummary.Raw {
        name: string;
    }
}
