/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const TimelineEntry: core.serialization.ObjectSchema<serializers.TimelineEntry.Raw, DevRev.TimelineEntry> =
    core.serialization.object({
        type: core.serialization.lazy(async () => (await import("../../..")).TimelineEntryType),
    });

export declare namespace TimelineEntry {
    interface Raw {
        type: serializers.TimelineEntryType.Raw;
    }
}
