/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const UserSummary: core.serialization.ObjectSchema<serializers.UserSummary.Raw, DevRev.UserSummary> =
    core.serialization.object({
        type: core.serialization.lazy(async () => (await import("../../..")).UserType),
    });

export declare namespace UserSummary {
    interface Raw {
        type: serializers.UserType.Raw;
    }
}
