/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const WorksCreateRequestTicket: core.serialization.ObjectSchema<
    serializers.WorksCreateRequestTicket.Raw,
    DevRev.WorksCreateRequestTicket
> = core.serialization.object({
    revOrg: core.serialization.property("rev_org", core.serialization.string().optional()),
    severity: core.serialization.lazy(async () => (await import("../../..")).TicketSeverity).optional(),
});

export declare namespace WorksCreateRequestTicket {
    interface Raw {
        rev_org?: string | null;
        severity?: serializers.TicketSeverity.Raw | null;
    }
}
