/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { DevRev } from "@fern-api/devrev";
import * as core from "../../../../core";

export const Work: core.serialization.ObjectSchema<serializers.Work.Raw, DevRev.Work> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("../../..")).WorkType),
});

export declare namespace Work {
    interface Raw {
        type: serializers.WorkType.Raw;
    }
}
